In [1]:
###Project Kaggle
###Daniel Vu
###34645787

import sys
sys.path.insert(0,'./mltools')

import numpy as np
import matplotlib.pyplot as plt
import mltools as ml
import seaborn as sns
import pandas as pd

import sklearn.model_selection
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn import svm

X_data = np.genfromtxt('./data/X_train.txt',delimiter=',')
Y_data = np.genfromtxt('./data/Y_train.txt',delimiter=None)
X_test = np.genfromtxt('./data/X_test.txt',delimiter=',')

X_train,X_valid,Y_train,Y_valid = ml.splitData(X_data,Y_data,0.75)

print(len(X_train))

print(len(Y_train))

print(len(X_valid))

print(len(Y_valid))

print(len(X_test))


print(X_train)

print(Y_train)

print(X_valid)

print(Y_valid)

5567
5567
1856
1856
7422
[[4.970e+02 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [3.080e+02 0.000e+00 1.200e+01 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.169e+03 1.400e+01 7.316e+03 ... 0.000e+00 0.000e+00 0.000e+00]
 ...
 [9.240e+02 7.000e+00 3.248e+03 ... 0.000e+00 0.000e+00 0.000e+00]
 [4.550e+03 7.000e+00 2.644e+03 ... 0.000e+00 0.000e+00 0.000e+00]
 [3.850e+02 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]]
[0. 1. 1. ... 0. 1. 1.]
[[6.300e+01 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [9.030e+02 0.000e+00 8.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [6.720e+02 7.000e+00 6.000e+01 ... 0.000e+00 0.000e+00 0.000e+00]
 ...
 [7.154e+03 7.000e+00 1.288e+03 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.120e+03 7.000e+00 5.136e+03 ... 0.000e+00 0.000e+00 0.000e+00]
 [6.580e+02 7.000e+00 2.156e+03 ... 0.000e+00 0.000e+00 0.000e+00]]
[1. 1. 0. ... 1. 0. 0.]


In [10]:
#Boosted Learners: Gradient Boosting

gradientBoost = GradientBoostingClassifier(n_estimators=500,max_depth=10,min_samples_split=10,min_samples_leaf=2)
fitGradientBoost = gradientBoost.fit(X_train,Y_train)

gb = fitGradientBoost.predict_proba(X_test)
Yv = fitGradientBoost.predict(X_valid)
Yt = fitGradientBoost.predict(X_train)

print('Training AUC: ',roc_auc_score(Y_train,Yt))
print('Validation AUC: ',roc_auc_score(Y_valid,Yv))
print(gb)


np.savetxt('submission_gb.csv', np.vstack( (np.arange(len(gb)), gb[:,1]) ).T,'%d, %.2f', header = 'ID,Predicted', comments = '', delimiter=',')

Training AUC:  1.0
Validation AUC:  0.6430924550205157
[[9.57933338e-01 4.20666620e-02]
 [9.94910245e-01 5.08975484e-03]
 [9.13630983e-01 8.63690170e-02]
 ...
 [4.81395279e-01 5.18604721e-01]
 [6.06876428e-05 9.99939312e-01]
 [7.81128189e-01 2.18871811e-01]]


In [13]:
#Boosted Learners: Ada Boost

adaBoost = AdaBoostClassifier(n_estimators=500,base_estimator = DecisionTreeClassifier(max_depth=10,min_samples_split=10))
fitAdaBoost = adaBoost.fit(X_train,Y_train)

ab = fitAdaBoost.predict_proba(X_test)
Yv = fitAdaBoost.predict(X_valid)
Yt = fitAdaBoost.predict(X_train)

print('Training AUC: ',roc_auc_score(Y_train,Yt))
print('Validation AUC: ',roc_auc_score(Y_valid,Yv))
print(ab)


np.savetxt('submission_ab.csv', np.vstack( (np.arange(len(ab)), ab[:,1]) ).T,'%d, %.2f', header = 'ID,Predicted', comments = '', delimiter=',')

Training AUC:  1.0
Validation AUC:  0.6247311340651832
[[0.9099473  0.0900527 ]
 [0.98730583 0.01269417]
 [0.55438827 0.44561173]
 ...
 [0.38629578 0.61370422]
 [0.02929474 0.97070526]
 [0.88401708 0.11598292]]


In [4]:
#Random Forests

randomForest = RandomForestClassifier(n_estimators = 500,max_depth = 25,min_samples_leaf = 2, oob_score = True)

randomForest.fit(X_train,Y_train)

rf = randomForest.predict_proba(X_test)

Yv = randomForest.predict(X_valid)
Yt = randomForest.predict(X_train)

print('Training AUC: ',roc_auc_score(Y_train,Yt))
print('Validation AUC: ',roc_auc_score(Y_valid,Yv))
print(rf)


np.savetxt('submission_rf.csv', np.vstack( (np.arange(len(rf)), rf[:,1]) ).T,'%d, %.2f', header = 'ID,Predicted', comments = '', delimiter=',')

Training AUC:  0.9996427295462665
Validation AUC:  0.6425387451644803
[[0.67397242 0.32602758]
 [0.78823333 0.21176667]
 [0.48694103 0.51305897]
 ...
 [0.53913187 0.46086813]
 [0.18390351 0.81609649]
 [0.50136429 0.49863571]]


In [19]:
#Kernel Method: Support Vector Machines

supportVM = svm.SVC(C = 100000000, gamma = 0.0000000001 , probability = True)

supportVM.fit(X_train,Y_train)

s = supportVM.predict_proba(X_test)
Yv = supportVM.predict(X_valid)
Yt = supportVM.predict(X_train)

print('Training AUC: ',roc_auc_score(Y_train,Yt))
print('Validation AUC: ',roc_auc_score(Y_valid,Yv))
print(s)


np.savetxt('submission_s.csv', np.vstack( (np.arange(len(s)), s[:,1]) ).T,'%d, %.2f', header = 'ID,Predicted', comments = '', delimiter=',')

Training AUC:  1.0
Validation AUC:  0.5134255757013755
[[0.5        0.5       ]
 [0.5        0.5       ]
 [0.5        0.5       ]
 ...
 [0.44050738 0.55949262]
 [0.5        0.5       ]
 [0.5        0.5       ]]


In [6]:
#Neural Networks

neuralNetwork = MLPClassifier(solver = 'adam',random_state =0)
neuralNetwork.fit(X_train,Y_train)

nn = neuralNetwork.predict_proba(X_test)
Yv = neuralNetwork.predict(X_valid)
Yt = neuralNetwork.predict(X_train)

print('Training AUC: ',roc_auc_score(Y_train,Yt))
print('Validation AUC: ',roc_auc_score(Y_valid,Yv))
print(nn)


np.savetxt('submission_nn_adam.csv', np.vstack( (np.arange(len(nn)), nn[:,1]) ).T,'%d, %.2f', header = 'ID,Predicted', comments = '', delimiter=',')

Training AUC:  0.5419478493557773
Validation AUC:  0.50872107548698
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]


/Users/danielvu/miniconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [ ]:
#Complete of 5 Ensembles:
completeEnsemble = []

completeEnsemble = (gb + ab + rf)/3

np.savetxt('submission_vudh1_2.csv', np.vstack( (np.arange(len(completeEnsemble)), completeEnsemble[:,1]) ).T,'%d, %.2f', header = 'ID,Predicted', comments = '', delimiter=',')